DEFAULT_MODEL_PATH = "models/artifacts/fraud_model.joblib"
DEFAULT_ENCODER_PATH = "models/encoders/preprocessing.joblib"

DEFAULT_THRESHOLD_ALLOW = 0.05
DEFAULT_THRESHOLD_BLOCK = 0.15

# Business defaults
DEFAULT_COST_FP = 50
DEFAULT_COST_FN = 2000
DEFAULT_REVIEW_COST = 20
DEFAULT_RECOVERY_RATE = 0.15
DEFAULT_REVENUE_PER_TXN = 5